apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: strategic-hyena-go 
  janus-idp.io/tekton: strategic-hyena-go
  backstage.io/kubernetes-id: strategic-hyena-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: strategic-hyena-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  