apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: strategic-hyena-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: strategic-hyena-go 
  name: strategic-hyena-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: strategic-hyena-go 
